### PR TITLE
update to add setting for fixing a seed before execution of f and g f…

### PR DESCRIPTION
**Pull request by lucidrains**
…unctions

@RobinBruegger @ag1988 Although not elegant, I believe this should fix the problem

### CODE REVIEW

**Comment by RobinBruegger** [comment]
Thanks again for the PR @lucidrains . I refactored the code a bit. Functionally, it should be unchanged. Otherwise, please let me know. 

I have created version 0.2.2 with this addition.

**Comment by lucidrains** [comment]
@RobinBruegger woohoo! thank you!

**Comment by ag1988** [comment]
@RobinBruegger <https://github.com/RobinBruegger> Thanks Robin.
Btw the set_seed(namespace) used in the init seed method might need a
prefix underscore.

**Comment by RobinBruegger** [comment]
@ag1988 Thanks for reporting that. Turns out I did not turn `fix_random_seed` on when testing :(
Fixed in v0.2.3

**Pull request merged**
